import { createAutoGeneratedUserReq } from "Requests/User.req";
import toast from "react-hot-toast";
import { useNavigate } from "react-router-dom";
import userStore from "stores/userStore";

const Entry = () => {
  const navigate = useNavigate();

  const user = userStore((state) => state);

  const goToLoginPage = () => {
    navigate("/login");
  };

  const goToHomePageWithoutLogin = async () => {
    try {
      const userInfo = await createAutoGeneratedUserReq();
      const { nickname, autoGenerated } = userInfo;
      console.log(userInfo);

      user.setUid(userInfo.uid);
      user.setNickname(nickname);
      user.setAutoGenerated(autoGenerated);
      navigate("/");
    } catch (err) {
      console.error(err);
      toast.error("오류가 발생했습니다.");
    }
  };

  return (
    <div className="entry page">
      <div className="logo">
        <div className="title">MIPS</div>
        <div className="subtitle">WEB 미니게임 플레이스테이션</div>
      </div>
      <div className="main-btn-container">
        <button className="main-btn highlight" onClick={goToLoginPage}>
          로그인
        </button>
        <button className="main-btn" onClick={goToHomePageWithoutLogin}>
          회원가입 없이 시작
        </button>
      </div>
    </div>
  );
};

export default Entry;
