import { create } from "zustand";
import { persist, createJSONStorage } from "zustand/middleware";

const userStore = create(
  persist(
    (set, get) => ({
      nickname: null,
      autoGenerated: true,
      setNickname: (nickname) => set({ nickname }),
      setAutoGenerated: (autoGenerated) => set({ autoGenerated }),
      clear: () => set({ nickname: null, autoGenerated: true }),
    }),
    {
      name: "mips/user",
      storage: createJSONStorage(() => sessionStorage),
    }
  )
);

export default userStore;
