import axios from "axios";
import { resolveUrl } from "./Common";

export const createAutoGeneratedUserReq = async () => {
  try {
    const resp = await axios.post(resolveUrl("user/create/auto-generated"));
    return resp.data;
  } catch (err) {
    throw err;
  }
};
